app:
  name: wolfai
  env: development
  port: 8080
  debug: true

database:
  host: localhost
  port: 5432
  name: wolfai
  user: postgres
  password: postgres
  sslmode: disable

auth:
  jwt_secret: your-secret-key
  token_expiry: 24h
  refresh_expiry: 720h

ml:
  model_path: ./internal/ml/models
  update_interval: 1h
  batch_size: 32

redis:
  host: localhost
  port: 6379
  password: ""

services:
  market_data:
    provider: alphavantage
    api_key: your-api-key
    update_interval: 5m