apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "filebeat-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "7.0.0"
      maxConcurrentShardRequests: 5
      interval: "Daily"
      logMessageField: "message"
      logLevelField: "level"
      
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: quantai
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false